### ISSUE TITLE
Beatable?

### ISSUE THREAD

**Issue by ErdaSin** [Vulcalien/minicraft-gba#1]
Is the game actually beatable? Im trying to find gold and im literally just finding iron and nothing else in the underground

**Comment by Vulcalien** [comment]
It seems like you are still in the first underground level. You have to find other stairs down.

**Comment by ErdaSin** [comment]
Oh, so there ARE other stairs down, im just exploring and still only seeing iron and rocks.
Thank you

**Comment by ErdaSin** [comment]
Altho im also curious, does sand ever "grow back" like grass does? Because sand is required for glass which is used for lanterns

**Comment by Vulcalien** [comment]
> does sand ever "grow back" like grass does?

Nope, it's in fact a finite resource, but there should be plenty in a world.
