### ISSUE TITLE
Asking about what's new in version 1.3

### ISSUE THREAD

**Issue by ErickN13** [Vulcalien/minicraft-gba#10]
What's new in this new Version? (1.3)

**Comment by Vulcalien** [comment]
Here's the Changelog, where I put the most significant changes made.
https://github.com/Vulcalien/minicraft-gba/blob/master/CHANGELOG.md

**Comment by ErickN13** [comment]
Thanks

**Comment by Vulcalien** [comment]
I also made a blog post about the update, http://vulcalien.net/blog/minicraft-gba-v1-3.

**Comment by ErickN13** [comment]
But it's normal when I update Minecraft 1.2.1 to 1.3, when I load my World from 1.2.1 using 1.3, Minicraft warns me that the Checksum is invalid but when I Load the World, does it load Normally?

**Comment by Vulcalien** [comment]
Yes, once the world is saved with the new version the warning will disappear.

**Comment by ErickN13** [comment]
Don't worry, I already got what I wanted lol
![10-02-2024 11.51.51 PM.png](https://github.com/Vulcalien/minicraft-gba/assets/144749573/f19d6fa8-910f-4e93-bdaa-c98564dbde6a)
