### ISSUE TITLE
No Caves?

### ISSUE THREAD

**Issue by LymeCPU** [Vulcalien/minicraft-gba#14]
Whenever I go up to the cave structures (the staircases), the rocks around them are unbreakable.Is this a problem with the version I have or have you just not added caves yet?

**Comment by Vulcalien** [comment]
Starts surrounded by hard to break rocks go up, you need the best pick to break those rocks.

To go to the cave levels, you need to find stairs that go down. They are in all versions of Minicraft for GBA.

**Comment by LymeCPU** [comment]
Thank you! I was wondering why I just couldn’t do anything with a stone pick.I look forward to playing the rest of the game! This kind of stuff is what I wish Minecraft adventure mode was: Minecraft but focused on combat and progression.
