### ISSUE TITLE
Is There A Way To Change The Save Type?

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [Vulcalien/minicraft-gba#2]
gbarunner2 on ds/dsi/3ds all hang on the save screen as they do not support the saving method is there anyway to change how the game saves?

**Comment by Vulcalien** [comment]
I'm not familiar with that emulator, however the game needs all 128 KB of save memory.
The only save type that big is 128 KB Flash ROM.

If the emulator does support 128 KB Flash ROM, maybe it doesn't detect the correct save type automatically. Refer to the emulator documentation in that case.

If it doesn't, I suggest using save states if supported.
