### ISSUE TITLE
Add Caves and Cliffs 1.18 to Minecraft GBA

### ISSUE THREAD

**Issue by ironboy36** [Vulcalien/minicraft-gba#5]
Pfft- I wanna see people's comments

**Comment by Vulcalien** [comment]
Unfortunately this isn't a demake of Minecraft but Min*i*craft instead. The cave system in this game is significantly simpler than Minecraft's.
Some modifications could be made to create different experiences other than the vanilla Minicraft caves, if anyone feels like going for it.
