### ISSUE TITLE
Update and leave the same as the original

### ISSUE THREAD

**Issue by ErickN13** [Vulcalien/minicraft-gba#7]
The GBA port is a little limited, should they leave it the same as the original?

**Comment by Vulcalien** [comment]
Not sure I get what you mean. Limited in what way?

**Comment by ErickN13** [comment]
> Not sure I get what you mean. Limited in what way?

I said that the Minicraft Game you made for the GBA is very limited, as the original JRE game has the ability to change the Character's Skin and Create Multiple Worlds, That's what I wanted to say

**Comment by ErickN13** [comment]
Your Minicraft Game is really cool, but it's very limited

**Comment by ErickN13** [comment]
I'm just saying that in the next version of Your GBA Minicraft, you make the game more similar to the original JRE game, understand?

**Comment by ErickN13** [comment]
Cool thing to add in the next version, would be to port the Beds, which are in the JRE game but are not in the GBA

**Comment by Vulcalien** [comment]
What you are describing seems like a mod of the game, like Minicraft Plus or some other. The original game, made in two days by Notch, contains nothing more than my GBA port.

**Comment by ErickN13** [comment]
> What you are describing seems like a mod of the game, like Minicraft Plus or some other. The original game, made in two days by Notch, contains nothing more than my GBA port.

But one thing I've noticed is that people prefer Minicraft Plus much more than Traditional Minicraft. Wouldn't it be better to have a version of Minicraft Plus for the GBA?

**Comment by ErickN13** [comment]
And that's not all, I know many friends who prefer Minicraft Plus Than traditional Minicraft, I know many people who hate traditional Minicraft and love Minicraft Plus

**Comment by Vulcalien** [comment]
As I said in #6, adding those features would require quite some work, because of the limitations of the GBA. With this version of Minicraft, I already pushed the RAM and Save Storage to the limit. Adding new tiles, or even new levels, would require finding a better way to store then in RAM and storage, which I currently can't think of.

My goal was to make a demake of the original Minicraft. Anyone is free to modify this code, as it is Free Software.

**Comment by ErickN13** [comment]
> As I said in #6, adding those features would require quite some work, because of the limitations of the GBA. With this version of Minicraft, I already pushed the RAM and Save Storage to the limit. Adding new tiles, or even new levels, would require finding a better way to store then in RAM and storage, which I currently can't think of.
> 
> My goal was to make a demake of the original Minicraft. Anyone is free to modify this code, as it is Free Software.

Okay, I understood everything, sorry for confusing you, bye
