### ISSUE TITLE
Game time incorrectly assumes 60 tps

### ISSUE THREAD

**Issue by Vulcalien** [Vulcalien/minicraft-gba#8]
In screen.c, screen_write_time calculates the seconds as time / 60. However, the tps is not 60, but about 59.7

**Comment by ErickN13** [comment]
But 59.7 is almost the same as 60

**Comment by Vulcalien** [comment]
> But 59.7 is almost the same as 60

Yep, almost but not exactly. The difference should be about 16 seconds every hour. It's rather small, but it should be easy to adjust the time to be perfect.

**Comment by Vulcalien** [comment]
Fixed in 968d36f! Time will now flow a little faster.

**Comment by ErickN13** [comment]
Boy, if I knew how to program like you do, I would create Minicraft for Ps1


See: I'm not asking you to create Minecraft for Ps1, I'm just mentioning something

**Comment by Vulcalien** [comment]
> create Minecraft for Ps1

It would take me a long time and effort to learn to code for the PS1. Plus, I'm not really interested in 3D retro consoles at the moment.

> if I knew how to program like you do

We all start somewhere, maybe that can be your first project.

**Comment by ErickN13** [comment]
Someday when it works I'll try :P
