### ISSUE TITLE
Save Slots

### ISSUE THREAD

**Issue by ErickN13** [Vulcalien/minicraft-gba#9]
I don't know if this could be possible because of the RAM, but there should be a way to save the game in slots like Metroid, Zelda, just like that

**Comment by Vulcalien** [comment]
Unfortunately, the save memory is already filled by one game. While the data format could be optimized to save much space, I doubt it would be enough to save even one more game.

The only viable solution to the problem would be to use non-standard cartridges with save memory greater than 128KB, but that would make it incompatible with most flash cartridges.
